
spring.application.name: GreetService
server.port: 8083
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
spring.boot.admin.client.url: http://localhost:8081